#!/bin/sh

if [ ! -e $HOME/.vim/bundle/Vundle.vim ]; then
  mkdir -p $HOME/.vim/bundle/
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi
vim -u $HOME/.vimrc +PluginInstall +qa
vim -u $HOME/.vimrc +PluginClean! +qa
