#!/bin/sh

mkdir -p $HOME/.vim/bundle/ $HOME/.config
ln -sf $HOME/.vim $HOME/.config/nvim
ln -sf $HOME/.vimrc  $HOME/.vim/init.vim

if [ ! -e $HOME/.vim/bundle/Vundle.vim ]; then
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi
vim -u $HOME/.vimrc +PluginInstall +PluginClean! +qall
