#!/bin/sh

if [ ! -e $HOME/.vim/bundle/vundle ]; then
  mkdir -p $HOME/.vim/bundle/
  git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
fi
vim -u $HOME/.vimrc +BundleInstall +qa
vim -u $HOME/.vimrc +BundleClean! +qa
